<?php

/**
 * This code was generated by ym.teruya
 */

namespace Trustalk\Rest\Api\Account\AccountList;

class AccountList
{
    /**
     * Construct the AccountList
     * @return Trustalk\Rest\Api\Account\AccountList
     */
    public function __construct() {
    }

    public function get() {
        return "AccountListGet";
    }
}
